### ISSUE TITLE
Error while Training

### ISSUE THREAD

**Issue by sainisanjay** [breadbread1984/R3DCNN#8]
Any idea how to resolve below issues. I am using `tensorflow version 1.12.0`
```
(tensor) sanjay@sanjay:~/workspace/mytutorial/R3DCNN$ python train_r3dcnn.py
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From train_r3dcnn.py:71: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
Traceback (most recent call last):
  File "train_r3dcnn.py", line 144, in <module>
    tf.app.run();
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_r3dcnn.py", line 20, in main
    gesture_classifier.train(input_fn = train_input_fn,steps = 200000,hooks = [logging_hook]);
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "train_r3dcnn.py", line 100, in action_model_fn
    tf.train.init_from_checkpoint("action_classifier_model",{v.name.split(':')[0]: v for v in tf.contrib.framework.get_variables_to_restore()});
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 187, in init_from_checkpoint
    _init_from_checkpoint, ckpt_dir_or_file, assignment_map)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/training/distribute.py", line 1053, in merge_call
    return self._merge_call(merge_fn, *args, **kwargs)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/training/distribute.py", line 1061, in _merge_call
    return merge_fn(self._distribution_strategy, *args, **kwargs)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 194, in _init_from_checkpoint
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 64, in load_checkpoint
    return pywrap_tensorflow.NewCheckpointReader(filename)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 326, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/home/sanjay/.virtualenvs/tensor/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for action_classifier_model
```

**Comment by sainisanjay** [comment]
@breadbread1984 can you help me to solve above issues. Thanks

**Comment by sainisanjay** [comment]
solved, thanks
